### ISSUE TITLE
[Compatibility Request] OptiFine

### ISSUE THREAD

**Issue by DearFox** [enjarai/show-me-your-skin#1]
Doesn't work with OptiFine
![image](https://user-images.githubusercontent.com/59219907/167475659-422a6e60-9c01-444f-af4f-b5fde68ee6ac.png)
![image](https://user-images.githubusercontent.com/59219907/167475795-ef67801e-a554-4aac-b63b-d94e1d5095b4.png)

**Comment by enjarai** [comment]
Since OptiFine is generally very incompatible with everything, and I'd recommend against using it at all, I consider this a low priority issue. 

If you need some OptiFine-specific features, take a look at [this](https://lambdaurora.dev/optifine_alternatives/) page, basically every feature is available as a standalone mod at this point.

I'll consider looking into fixing the incompatibility if I have some spare time.
