### ISSUE TITLE
Crashes with Physics Mod Pro cape physics

### ISSUE THREAD

**Issue by Byllfighter** [enjarai/show-me-your-skin#25]
Game crashes with Physics Mod Pro cape physics when I pressing F5

**Comment by enjarai** [comment]
Please provide a crash report and logs.

**Comment by Byllfighter** [comment]
[crash-2022-08-14_12.42.55-client.txt](https://github.com/enjarai/show-me-your-skin/files/9333022/crash-2022-08-14_12.42.55-client.txt)
[latest.log](https://github.com/enjarai/show-me-your-skin/files/9333023/latest.log)

**Comment by enjarai** [comment]
It's hard to tell without being able to see the source, but it's likely the author of the physics mod didn't do a null check at a certain point. This wouldn't be a problem in vanilla, but due to how my mod renders the config screen it causes issues here.

I can't fix this on my side, please report it to the author of the physics mod.
