### ISSUE TITLE
Crashing when accessing settings in the mod menu.

### ISSUE THREAD

**Issue by KateReller** [enjarai/show-me-your-skin#35]
When trying to change settings of this mod via the mod menu, the game crashes.

https://mclo.gs/uhEYwA8

**Comment by enjarai** [comment]
This seems to be an incompatibility with Wildfire's Female Gender Mod. They, like many other mods I've seen, are assuming that if an entity is being rendered, the player must be loaded into a world, which is not always the case.

This is not something I can fix from my side, please open an issue on their issue tracker.

The issue seems to occur here:
https://github.com/WildfireRomeo/WildfireFemaleGenderMod/blob/fabric-1.19/src/main/java/com/wildfire/render/GenderLayer.java#L93

It'll also potentially happen in any other place using `MinecraftClient#player` without a null-check.
