### ISSUE TITLE
pls fix

### ISSUE THREAD

**Issue by Robert3048** [enjarai/show-me-your-skin#37]
hello dear person who reads my issue. I have such a disturbing issue that i alomost get in a coma just by thinking about it. The person who uploaded this mod on the curseforge website, clearly forgot to add forge to the mod and i would like to ask for it to be fixed. Untul forge is added, this mod will be unplayable garbage pls fix

**Comment by enjarai** [comment]
Good morning/afternoon/evening dear person who made this issue, I hope this response finds you well. Though I appreciate the time you put into writing me, I'm afraid I'll have to point out a slight flaw in your logic. You see, I feel you might have gotten things the wrong way around here, since, as opposed to what you imply, the Forge modloader itself is utterly unplayable garbage, and has been that way for quite a while. I sincerely hope you don't mind me correcting this grave error in judgement, and would ask you to kindly go fuck yourself.
