### ISSUE TITLE
[Feature Request] Elytra Support on Chestplate setting

### ISSUE THREAD

**Issue by SteveKunG** [enjarai/show-me-your-skin#5]
As title said, that would be appreciated. Great mod by the way!

**Comment by enjarai** [comment]
The title is kind of vague, but I assume you mean an option to hide the elytra?

Since the elytra rendering is entirely seperate from the armor rendering, I'll add a toggle button to hide the elytra in the next update.

![image](https://user-images.githubusercontent.com/38552516/170787271-cfdaa401-6ac9-477c-bbed-3597c2d11886.png)
